language: scala
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
jdk: oraclejdk8
script:
- sbt ++$TRAVIS_SCALA_VERSION test
- sbt ++$TRAVIS_SCALA_VERSION assembly
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
scala: 2.12.2
